// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright The XCSoar Project

package org.xcsoar

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.util.Log

/**
 * Image decoding for the core's map (core/map/AndroidBitmap.cpp): what
 * the old UI's NativeView does for XCSoar.  The icons are XCSoar's own
 * drawables, generated by its build ("make core-drawables").
 *
 * Lives in package org.xcsoar for the package-private [BitmapUtil],
 * which is reused unchanged (mobile/docs/DECISIONS.md D13).
 */
object CoreGraphics {
    private const val TAG = "XCSoar"
    private lateinit var context: Context

    /** Before the map is attached. */
    fun initialise(context: Context) {
        this.context = context.applicationContext
    }

    @JvmStatic
    fun loadResourceBitmap(name: String): Bitmap? {
        val resources = context.resources
        @Suppress("DiscouragedApi")  // the core names its icons, like XCSoar
        val id = resources.getIdentifier(name, "drawable", context.packageName)
        if (id == 0) {
            Log.e(TAG, "Resource not found: drawable/$name")
            return null
        }
        val options = BitmapFactory.Options().apply { inScaled = false }
        return BitmapFactory.decodeResource(resources, id, options)
    }

    @JvmStatic
    fun loadFileBitmap(path: String): Bitmap? = BitmapFactory.decodeFile(path)

    /** @param result receives texture id, width, height, allocated width and height */
    @JvmStatic
    fun bitmapToTexture(bitmap: Bitmap, alpha: Boolean, result: IntArray): Boolean =
        BitmapUtil.bitmapToOpenGL(bitmap, false, alpha, result)

    /** What OpenGL::SetupContext() detected; textures follow it. */
    @JvmStatic
    fun setTextureNonPowerOfTwo(value: Boolean) {
        NativeView.textureNonPowerOfTwo = value
    }
}
